services:
  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: refat
      POSTGRES_PASSWORD: refat123
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: refat@example.com
      PGADMIN_DEFAULT_PASSWORD: refat123
    ports:
      - "8080:80"

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    depends_on:
      - redis

volumes:
  redis_data:
  redisinsight_data: